[firebase]
type = "service_account"
project_id = "college-notes-hub-4416d"
private_key_id = "746e7b88b7bc1f194576852a96d116d12d3d3898"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmrm+gW+kO9pNf
fER5O3r6CVFdnfosKCGizDHmfmdTxJrFXAo04RJc3DauVoBtj07mAroFsv7GkLI8
g7JJOqotzESD76DtqV3CwFREkBzoYSDkrvWKWx/imyUbuDdLq2kf2ujgfMu9SWn8
6ZWds+uKYe8CjVVH8TbLN/bt0Dq5B6DlXNLx76UbLGIjInv5dz65jtJOOxdeZxqk
bWsAUxaTll7skptOd29A8eK5M/kHPSgJLCCmATjRs8av++agF7Jb0BY185ON6apz
goqDw7NX1G8lsrfU8QTIi/m4LmxWSk8BdgLxCvSfk4rs0KAG4tcVNVTbHCjmSNZx
Y9j8UC5dAgMBAAECggEAJUPCeRuTU2EVObfSpzgBGn2Sz1dOYyjlvDvivCFugG/o
Gk+liIT5UgF5yChWtiff/9SEOln2U/ZtotHevjh7a5nLh6O/WuMOr0fIjzuY+usc
K4RiKPiOfF8rQLNCyYwdCJ4simPcOQl8xKqEZKmg82NJyExI0LjBA1YTwr9XIZ6S
SCrcaFfOYGej3j2jrDV9cAienXal/X/xK8vsIu/ND6w5uX0xbu9nE3vGHxQNXBwg
jiXSuXNl98lJl6T5csyYf3LzGOEwbvL5U9pJw4KEODOiny9G2x2OjoEDRZNUAsR5
VyxEQ5teoh5GVyFl8mNvq+A+d6OGPd6/Hr0C3wR4gQKBgQDhOQSX/395CnvLdbAL
aAi51Lq9sFweNwmtnNwZgSgDW73oFlmyRX1slff6MomemV+h6mqfrdoyY+4JiPws
5f22LFVeDyg0HGYK+7epLh+LRKRkDeHkefUwKJSrrZTZ/1DeWeO5VdSCaTPZdMW6
GmlHYS7yfNm+dSKC68Ahc8gg+QKBgQC9dXZpb75mNViGXFm8XUZf5X3K2S8TFGQ6
b2b3pAAYDLO/oVYAp62EihQ6YpCyWHQe/thpbgQ7I36RmIWujH+vPOhUSNMtZrEd
fyMwxA860809/f5tRusrAWXEURJPfXlnOdGvk0B4i9S/bAbBhAm0ViqvYwwCkF9W
bm8z7v+1hQKBgQCgIIzOkJ4N7dE0R9lBUtcZYFDgurnT1aew4txt2bEcKibsEq/1
GojhIgLrxPCpbTxb/zGNk+qVdwzvhJBeT6rB0eVj+XzJCAPY/TyIMT3GI6iJZoFb
kwYrFj8VjFVPZMIXRGuvAoITsj5l9ir6dPqzADqDtxaM3fUKhhjU79+y6QKBgCuS
OAlHiaI34oQD+R841FZ5kNR13j2lEufddvC85sihIzWPBRhhd6ZjmwNSZ7ScYxg9
w8d7Zb20DAev7A6YgUTr3QKFPQvT8ie2dYFhlZ8R1sHLCBhZlvvs9lqPyoY9dQ4o
XfDjDJCsl+DuFx+qHhE7P9XWEY0FZueZvjlTXbuBAoGAHfuv5HLynVZBkhLdidQC
3h7NEWml2pVtmCS1q6SYuMcIKdfwsJZCDWRdy+3+0eq8LqLc1dEmxM2Xd7wl0Mts
zsN+tPl8IrZyubQEboyn1fkgmsiIKBn4daHDy0YHUgDTScT3HS2NtRf0yR9O5rZX
2zRcnlDSuyG/2j/h46UW0XA=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@college-notes-hub-4416d.iam.gserviceaccount.com"
client_id = "100902773531941249552"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40college-notes-hub-4416d.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



# .streamlit/secrets.toml
[email]
sender = "hardikaneja20@gmail.com"
password = "eemoqqeatdrxgoqw"  # <- yeh app password daalo
